### ISSUE TITLE
Critical injection failure when used with architectury mod

### ISSUE THREAD

**Issue by Soochaehwa** [DrexHD/AntiXray#15]
```
[11:36:13] [Server thread/ERROR]: Critical injection failure: LVT in net/minecraft/class_2852::method_12395(Lnet/minecraft/class_3218;Lnet/minecraft/class_4153;Lnet/minecraft/class_1923;Lnet/minecraft/class_2487;)Lnet/minecraft/class_2839; has incompatible changes at opcode 787 in callback architectury.mixins.json:MixinChunkSerializer->@Inject::load(Lnet/minecraft/class_3218;Lnet/minecraft/class_4153;Lnet/minecraft/class_1923;Lnet/minecraft/class_2487;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_2843;ZLnet/minecraft/class_2499;I[Lnet/minecraft/class_2826;ZLnet/minecraft/class_2802;Lnet/minecraft/class_3568;Lnet/minecraft/class_2378;JLnet/minecraft/class_2806$class_2808;Lnet/minecraft/class_6749;Lnet/minecraft/class_2791;)V from mod architectury.
 Expected: [Lnet/minecraft/class_2843;, Z, Lnet/minecraft/class_2499;, I, [Lnet/minecraft/class_2826;, Z, Lnet/minecraft/class_2802;, Lnet/minecraft/class_3568;, Lnet/minecraft/class_2378;, J, Lnet/minecraft/class_2806$class_2808;, Lnet/minecraft/class_6749;, Lnet/minecraft/class_2791;]
    Found: [Lnet/minecraft/class_1923;, Lnet/minecraft/class_2843;, Z, Lnet/minecraft/class_2499;, I, [Lnet/minecraft/class_2826;, Z, Lnet/minecraft/class_2802;, Lnet/minecraft/class_3568;, Lnet/minecraft/class_2378;, J, Lnet/minecraft/class_2806$class_2808;, Lnet/minecraft/class_6749;]
Available: [Lnet/minecraft/class_1923;, Lnet/minecraft/class_2843;, Z, Lnet/minecraft/class_2499;, I, [Lnet/minecraft/class_2826;, Z, Lnet/minecraft/class_2802;, Lnet/minecraft/class_3568;, Lnet/minecraft/class_2378;, J, Lnet/minecraft/class_2806$class_2808;, Lnet/minecraft/class_6749;, Lnet/minecraft/class_2791;]
[11:36:13] [Server thread/ERROR]: Couldn't load chunk [-1, -1]
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2852 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:234) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:136) ~[fabric-loader-0.12.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_3898.method_17256(class_3898.java:594) ~[intermediary-server-1.18.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:552) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:561) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_3215.method_12121(class_3215.java:142) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_1937.method_8402(class_1937.java:189) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_4538.method_22342(class_4538.java:140) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_1937.method_8497(class_1937.java:183) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_5322.method_29194(class_5322.java:23) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_5322.method_29196(class_5322.java:64) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.server.MinecraftServer.method_27901(MinecraftServer.java:449) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:380) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:327) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_3176.method_3823(class_3176.java:182) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:657) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server-1.18.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229) ~[fabric-loader-0.12.8.jar:?]
	... 23 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_2852::method_12395(Lnet/minecraft/class_3218;Lnet/minecraft/class_4153;Lnet/minecraft/class_1923;Lnet/minecraft/class_2487;)Lnet/minecraft/class_2839; has incompatible changes at opcode 787 in callback architectury.mixins.json:MixinChunkSerializer->@Inject::load(Lnet/minecraft/class_3218;Lnet/minecraft/class_4153;Lnet/minecraft/class_1923;Lnet/minecraft/class_2487;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_2843;ZLnet/minecraft/class_2499;I[Lnet/minecraft/class_2826;ZLnet/minecraft/class_2802;Lnet/minecraft/class_3568;Lnet/minecraft/class_2378;JLnet/minecraft/class_2806$class_2808;Lnet/minecraft/class_6749;Lnet/minecraft/class_2791;)V from mod architectury.
 Expected: [Lnet/minecraft/class_2843;, Z, Lnet/minecraft/class_2499;, I, [Lnet/minecraft/class_2826;, Z, Lnet/minecraft/class_2802;, Lnet/minecraft/class_3568;, Lnet/minecraft/class_2378;, J, Lnet/minecraft/class_2806$class_2808;, Lnet/minecraft/class_6749;, Lnet/minecraft/class_2791;]
    Found: [Lnet/minecraft/class_1923;, Lnet/minecraft/class_2843;, Z, Lnet/minecraft/class_2499;, I, [Lnet/minecraft/class_2826;, Z, Lnet/minecraft/class_2802;, Lnet/minecraft/class_3568;, Lnet/minecraft/class_2378;, J, Lnet/minecraft/class_2806$class_2808;, Lnet/minecraft/class_6749;]
Available: [Lnet/minecraft/class_1923;, Lnet/minecraft/class_2843;, Z, Lnet/minecraft/class_2499;, I, [Lnet/minecraft/class_2826;, Z, Lnet/minecraft/class_2802;, Lnet/minecraft/class_3568;, Lnet/minecraft/class_2378;, J, Lnet/minecraft/class_2806$class_2808;, Lnet/minecraft/class_6749;, Lnet/minecraft/class_2791;]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:545) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:495) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1374) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:229) ~[fabric-loader-0.12.8.jar:?]
	... 23 more
```

Logs like this are repeated

**Comment by NoThrottle** [comment]
Yup, I also get the same error. https://mcpaste.io/a13e1e9cc71c113d

**Comment by DrexHD** [comment]
Hey @Soochaehwa and @NoThrottle, thanks for reporting this bug. I just pushed a fix for this issue. Can you please confirm that the fix actually works for you, by downloading the fixed version from [github actions](https://github.com/DrexHD/AntiXray/suites/4759298440/artifacts/132095137)!

-Drex

**Comment by SevenThomsen** [comment]
> Hey @Soochaehwa and @NoThrottle, thanks for reporting this bug. I just pushed a fix for this issue. Can you please confirm that the fix actually works for you, by downloading the fixed version from [github actions](https://github.com/DrexHD/AntiXray/suites/4759298440/artifacts/132095137)!
> 
> -Drex

I was having the same issue as above while running a server for the Better Minecraft modpack, which has Architectury. I can confirm that version fixed the issue for me, and it is now successfully running on my server.

**Comment by DrexHD** [comment]
Thanks for the information!

**Comment by NoThrottle** [comment]
Everything works now! Thanks!
