### ISSUE TITLE
Server closed when player joined

### ISSUE THREAD

**Issue by Artin0123** [DrexHD/AntiXray#30]
I made a fabric server with [Tutorials](https://fabricmc.net/wiki/player:tutorials:server:windows), and I only have this mod in the mods folder. 
It crashed when I join the server. What could be the problem?
Server version is 1.19.3.
Thanks in advance.

[20:30:49] [Server thread/INFO]: Artin0123 joined the game
[20:30:49] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: me/lucko/fabric/api/permissions/v0/Permissions
        at me.drex.antixray.fabric.AntiXrayFabric.canBypassXray(AntiXrayFabric.java:19) ~[anti-xray-1.2.8-Fabric-1.19.3.jar:?]
        at net.minecraft.class_3898.redirect$zzb000$updateChunkPacket(class_3898.java:1491) ~[server-intermediary.jar:?]
        at net.minecraft.class_3898.method_18715(class_3898.java:1305) ~[server-intermediary.jar:?]
        at net.minecraft.class_3898.method_17241(class_3898.java:916) ~[server-intermediary.jar:?]
        at net.minecraft.class_3898.method_18714(class_3898.java:1080) ~[server-intermediary.jar:?]
        at net.minecraft.class_3898.method_18701(class_3898.java:1212) ~[server-intermediary.jar:?]
        at net.minecraft.class_3215.method_18755(class_3215.java:482) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1547) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1525) ~[server-intermediary.jar:?]
        at net.minecraft.class_5579.method_31847(class_5579.java:217) ~[server-intermediary.jar:?]
        at net.minecraft.class_5579.method_31820(class_5579.java:187) ~[server-intermediary.jar:?]
        at net.minecraft.class_5579.method_31818(class_5579.java:168) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18771(class_3218.java:891) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18213(class_3218.java:877) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14570(class_3324.java:248) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_33800(class_3248.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_14384(class_3248.java:118) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.lucko.fabric.api.permissions.v0.Permissions
        at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 26 more

**Comment by DrexHD** [comment]
I am a bit confused why this happened and currently don't have the time to look into this, but adding the jar from https://github.com/lucko/fabric-permissions-api/releases/tag/v0.2 should hopefully fix this.
