### ISSUE TITLE
Server Crash At Startup, Stops Before I Have Time To Read The Reason.

### ISSUE THREAD

**Issue by LillaLyran** [DrexHD/AntiXray#48]
In My Fabric 1.16.5 Server I Have [Lithum, Fabric API, Fabric Tpa], But When I Add The Anti Xray Mod To The Server, I Get Crashes Before It Can Even Start, I Have A Crash Log That I Found In The Server Files:

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-07-15 19:02
Description: Exception in server tick loop

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3898 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_3215.<init>(class_3215.java:88)
	at net.minecraft.class_3218.<init>(class_3218.java:191)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:368)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:335)
	at net.minecraft.class_3176.method_3823(class_3176.java:179)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 12 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [antixray.mixins.json:ChunkMapMixin from mod antixray] from phase [DEFAULT] in config [antixray.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Redirect annotation on initValues could not find any targets matching 'lambda$scheduleChunkLoad$14' in net.minecraft.class_3898. Using refmap anti-xray-mc1.16.5-refmap.json [PREINJECT Applicator Phase -> antixray.mixins.json:ChunkMapMixin from mod antixray -> Prepare Injections ->  -> redirect$zza000$antixray$initValues(Lnet/minecraft/class_1923;Lnet/minecraft/class_2843;)Lnet/minecraft/class_2839; -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.RedirectInjectionInfo.<init>(RedirectInjectionInfo.java:44)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710)
	at com.llamalad7.mixinextras.wrapper.factory.FactoryRedirectWrapperImpl.<init>(FactoryRedirectWrapperImpl.java:30)
	at com.llamalad7.mixinextras.wrapper.WrapperInjectionInfo.<init>(WrapperInjectionInfo.java:29)
	at com.llamalad7.mixinextras.wrapper.factory.FactoryRedirectWrapperInjectionInfo.<init>(FactoryRedirectWrapperInjectionInfo.java:13)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 751287880 bytes (716 MB) / 1060110336 bytes (1011 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 1 total; -Xmx2G
	Fabric Mods: 
		antixray: AntiXray 1.1.0
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		fabric: Fabric API 0.42.0+1.16
		fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+3cc0f0907d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.6+3cc0f0907d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
		fabricloader: Fabric Loader 0.15.11
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.16.5
		mixinextras: MixinExtras 0.3.5
	Player Count: 0 / 20; []
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by DrexHD** [comment]
I am sorry, but 1.16.5 is to old for me to waste my time looking into issues!
