### ISSUE TITLE
Server crashes seemingly at random

### ISSUE THREAD

**Issue by xela-the-proto** [DrexHD/AntiXray#55]
The server randomly crashes in the Nether and as far as i can understand it looks xray is doing something funky when sending a packet

```
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 2024-08-27 21:38:49
Description: Exception in server tick loop

java.lang.ClassCastException: class net.minecraft.class_2841$class_6563$Anonymous$bee7129e33f84d09a5a916499892683c cannot be cast to class net.minecraft.class_6880 (net.minecraft.class_2841$class_6563$Anonymous$bee7129e33f84d09a5a916499892683c and net.minecraft.class_6880 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @2d554825)
	at net.minecraft.class_2378$1.method_10206(class_2378.java:186)
	at net.minecraft.class_2834.method_12290(class_2834.java:100)
	at net.minecraft.class_2841$class_6561.method_38306(class_2841.java:321)
	at net.minecraft.class_2841.method_12327(class_2841.java:275)
	at net.minecraft.class_2826.method_12260(class_2826.java:176)
	at net.minecraft.class_6603.method_38589(class_6603.java:80)
	at net.minecraft.class_6603.<init>(class_6603.java:42)
	at net.minecraft.class_2672.mixinextras$bridge$newclass_6603$19(class_2672.java)
	at net.minecraft.class_2672.wrapOperation$zze000$antixray$setChunkPacketInfoArgument(class_2672.java:559)
	at net.minecraft.class_2672.<init>(class_2672.java:28)
	at net.minecraft.class_8608.method_52388(class_8608.java:88)
	at net.minecraft.class_8608.mixinextras$bridge$method_52388$18(class_8608.java)
	at net.minecraft.class_8608.wrapOperation$zzk000$antixray$setBatchStartPacketArgument(class_8608.java:556) <---
	at net.minecraft.class_8608.method_52386(class_8608.java:81)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1045)
	at net.minecraft.class_3176.method_3813(class_3176.java:299)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by xela-the-proto** [comment]
To add any context i was running shaders + the server auto downloads a resource pack

**Comment by xela-the-proto** [comment]
oh i forgot minecraft version 1.21 with Fabric API 0.102.0+1.21

**Comment by DrexHD** [comment]
Make sure to use v1.4.6 and reproduce with that. If the issue still persists send the full crash report!

**Comment by xela-the-proto** [comment]
![image](https://github.com/user-attachments/assets/f8f397be-6ac2-4ca7-b3a3-ab18e413cb01)
im on 1.21 tho and there are none for that version

**Comment by DrexHD** [comment]
1.21.1 is basically identical to 1.21! Very few mods should break. You should update to 1.21.1, but the 1.21.1 version should also work on 1.21.

**Comment by xela-the-proto** [comment]
> 1.21.1 is basically identical to 1.21! Very few mods should break. You should update to 1.21.1, but the 1.21.1 version should also work on 1.21.

Ill try to update but i had some stuff break if i remember

**Comment by xela-the-proto** [comment]
Srry i completely forgot also it seems the issue resolved itself so good enough i guess
