### ISSUE TITLE
Crash on singleplayer with mod added

### ISSUE THREAD

**Issue by Garagoth** [DrexHD/AntiXray#8]
Added to working minecraft with fabric (1.17.1, fabric latest) antixray mod and tried to create new world. Crashed after clicking on "Create new world."
Config file is nowhere to be found.
Only other mod is advanced xray - so I can test how this works...

antixray version: 1.1.0

```
[08/10/2021 15:12:51 PM] [Server thread/INFO]: Starting integrated minecraft server version 1.17.1
[08/10/2021 15:12:51 PM] [Server thread/INFO]: Generating keypair
[08/10/2021 15:12:51 PM] [Server thread/ERROR]: Encountered an unexpected exception
[08/10/2021 15:12:51 PM] java.lang.NullPointerException: Cannot invoke "com.moandjiezana.toml.Toml.contains(String)" because "toml" is null
[08/10/2021 15:12:51 PM] 	at me.drex.antixray.config.WorldConfig.loadValues(WorldConfig.java:35) ~[anti-xray-mc1.17.1-1.1.0.jar:?]
[08/10/2021 15:12:51 PM] 	at me.drex.antixray.config.WorldConfig.<init>(WorldConfig.java:26) ~[anti-xray-mc1.17.1-1.1.0.jar:?]
[08/10/2021 15:12:51 PM] 	at net.minecraft.class_1937.initValues(class_1937.java:4583) ~[intermediary-client-1.17.1.jar:?]
[08/10/2021 15:12:51 PM] 	at net.minecraft.class_3218.handler$ccf000$onInit(class_3218.java:9091) ~[intermediary-client-1.17.1.jar:?]
[08/10/2021 15:12:51 PM] 	at net.minecraft.class_3218.<init>(class_3218.java:160) ~[intermediary-client-1.17.1.jar:?]
[08/10/2021 15:12:51 PM] 	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:383) ~[intermediary-client-1.17.1.jar:?]
[08/10/2021 15:12:51 PM] 	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:350) ~[intermediary-client-1.17.1.jar:?]
[08/10/2021 15:12:51 PM] 	at net.minecraft.class_1132.method_3823(class_1132.java:71) ~[intermediary-client-1.17.1.jar:?]
[08/10/2021 15:12:51 PM] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-client-1.17.1.jar:?]
[08/10/2021 15:12:51 PM] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-client-1.17.1.jar:?]
[08/10/2021 15:12:51 PM] 	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Garagoth** [comment]
Also, version for MC 1.16.5 requires java 16 instead of default one, but after running with java 16 i get same result:
```
[08/10/2021 15:30:00 PM] [Server thread/ERROR]: Encountered an unexpected exception
[08/10/2021 15:30:00 PM] java.lang.NullPointerException: Cannot invoke "com.moandjiezana.toml.Toml.contains(String)" because "toml" is null
[08/10/2021 15:30:00 PM] 	at me.drex.antixray.config.WorldConfig.loadValues(WorldConfig.java:35) ~[anti-xray-mc1.16.5-1.1.0.jar:?]
[08/10/2021 15:30:00 PM] 	at me.drex.antixray.config.WorldConfig.<init>(WorldConfig.java:26) ~[anti-xray-mc1.16.5-1.1.0.jar:?]
[08/10/2021 15:30:00 PM] 	at net.minecraft.class_1937.initValues(class_1937.java:1228) ~[intermediary-client-1.16.5.jar:?]
[08/10/2021 15:30:00 PM] 	at net.minecraft.class_3218.handler$zzj000$onInit(class_3218.java:1589) ~[intermediary-client-1.16.5.jar:?]
[08/10/2021 15:30:00 PM] 	at net.minecraft.class_3218.<init>(class_3218.java:167) ~[intermediary-client-1.16.5.jar:?]
[08/10/2021 15:30:00 PM] 	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:368) ~[intermediary-client-1.16.5.jar:?]
[08/10/2021 15:30:00 PM] 	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:335) ~[intermediary-client-1.16.5.jar:?]
[08/10/2021 15:30:00 PM] 	at net.minecraft.class_1132.method_3823(class_1132.java:67) ~[intermediary-client-1.16.5.jar:?]
[08/10/2021 15:30:00 PM] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645) ~[intermediary-client-1.16.5.jar:?]
[08/10/2021 15:30:00 PM] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-client-1.16.5.jar:?]
[08/10/2021 15:30:00 PM] 	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by DrexHD** [comment]
Is there a specific reason you need client-side anti x-ray (Anti x-ray is intended to be installed on server-side to hide ores from malicious players)?
