### ISSUE TITLE
Exception in server tick loop after upgrading Fabric API

### ISSUE THREAD

**Issue by the-english-breaker** [DrexHD/AntiXray#9]
```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 09.10.2021, 23:00
Description: Exception in server tick loop

java.lang.IndexOutOfBoundsException: Index 20342 out of bounds for length 20342
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
        at java.base/java.util.Objects.checkIndex(Unknown Source)
        at java.base/java.util.ArrayList.get(Unknown Source)
        at eu.pb4.polymer.other.DualList.get(DualList.java:151)
        at net.minecraft.class_2361.method_10200(class_2361.java:57)
        at net.minecraft.class_2816.method_12288(class_2816.java:31)
        at me.drex.antixray.util.ChunkPacketBlockControllerAntiXray.<init>(ChunkPacketBlockControllerAntiXray.java:130)
        at net.minecraft.class_1937.initValues(class_1937.java:5084)
        at net.minecraft.class_3218.handler$baa000$onInit(class_3218.java:6091)
        at net.minecraft.class_3218.<init>(class_3218.java:160)
        at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:383)
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:350)
        at net.minecraft.class_3176.method_3823(class_3176.java:184)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
        at java.base/java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.17.1
        Minecraft Version ID: 1.17.1
        Operating System: Linux (amd64) version 4.19.0-17-amd64
        Java Version: 16.0.1, AdoptOpenJDK
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
        Memory: 695636480 bytes (663 MiB) / 2778726400 bytes (2650 MiB) up to 2778726400 bytes (2650 MiB)
        CPUs: 2
        Processor Vendor: GenuineIntel
        Processor Name: Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
        Identifier: Intel64 Family 6 Model 79 Stepping 1
        Microarchitecture: Broadwell (Server)
        Frequency (GHz): 3,60
        Number of physical packages: 2
        Number of physical CPUs: 2
        Number of logical CPUs: 2
        Graphics card #0 name: unknown
        Graphics card #0 vendor: unknown
        Graphics card #0 VRAM (MB): 0,00
        Graphics card #0 deviceId: unknown
        Graphics card #0 versionInfo: unknown
        Virtual memory max (MB): 1973,44
        Virtual memory used (MB): 2879,38
        Swap memory total (MB): 0,00
        Swap memory used (MB): 0,00
        JVM Flags: 4 total; -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -Xms2650M -Xmx2650M
        Fabric Mods: 
                antixray: AntiXray 1.1.0
                bfapi: BFAPI 1.1.8
                cloth-basic-math: Cloth Basic Math 0.5.1
                cloth-config2: Cloth Config v5 5.0.38
                club_minnced_discord-webhooks: discord-webhooks 0.5.8
                cmdspy: Command Spy 1.2.3
                com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.10.1
                com_fasterxml_jackson_core_jackson-core: jackson-core 2.10.1
                com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.10.1
                com_github_shevek_parallelgzip: parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
                com_moandjiezana_toml_toml4j: toml4j 0.7.2
                com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
                com_squareup_okhttp3_okhttp: okhttp 3.14.9
                com_squareup_okio_okio: okio 1.17.2
                com_vdurmont_emoji-java: emoji-java 5.1.1
                dynmap: Dynmap 3.2.1
                editsign: EditSign 2.2.4
                fabric: Fabric API 0.40.6+1.17
                fabric-api-base: Fabric API Base 0.3.0+a02b446318
                fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
                fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
                fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
                fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
                fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
                fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
                fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
                fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
                fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
                fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
                fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
                fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
                fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
                fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
                fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
                fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
                fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
                fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
                fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
                fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
                fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
                fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
                fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
                fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
                fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
                fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.11+7931163218
                fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
                fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
                fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
                fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
                fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
                fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
                fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
                fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.0+7931163218
                fabricloader: Fabric Loader 0.11.7
                fabricsit: FabricSit 1.6.3
                fallingtree: FallingTree 2.14.0
                farsighted-mobs: Farsighted Mobs 1.1-1.17
                fdlink: Fabric <-> Discord Link 0.9.8
                fdlink_1_12_2: Fabric <-> Discord Link 0.9.8
                fdlink_1_15_2: Fabric <-> Discord Link 0.9.8
                fdlink_1_16: Fabric <-> Discord Link 0.9.8
                fdlink_1_7_10: Fabric <-> Discord Link 0.9.8
                fdlink_1_8_9: Fabric <-> Discord Link 0.9.8
                fdlink_api: Fabric <-> Discord Link API 0.1.1
                fdlink_common: Fabric <-> Discord Link 0.9.8
                golfiv: Golf IV 0.4.0
                hologram-api: Hologram API 0.2.1+1.17.1
                java: OpenJDK 64-Bit Server VM 16
                ledger: Ledger 1.1.1
                lithium: Lithium 0.7.4
                luckperms: LuckPerms 5.3.69
                minecraft: Minecraft 1.17.1
                net_dv8tion_jda: JDA 4.3.0_323
                net_sf_trove4j_trove4j: trove4j 3.0.3
                org_apache_commons_commons-collections4: commons-collections4 4.1
                org_apache_commons_commons-compress: commons-compress 1.19
                org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
                org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
                org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
                org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
                org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
                org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
                org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
                org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
                org_json_json: json 20210307
                org_slf4j_slf4j-api: slf4j-api 1.7.25
                org_slf4j_slf4j-nop: slf4j-nop 1.7.25
                org_tukaani_xz: xz 1.8
                packet_tweaker: Packet Tweaker 0.2.0+1.17.1
                placeholder-api: Placeholder API 1.1.1+1.17.1
                polymer: Polymer 0.1.5+1.17.1
                server_translations_api: Server Translations API 1.4.5+1.17
                sgui: SGui 1.0.0-rc4+1.17.1
                spark: spark 1.6.2
                textile_backup: Textile Backup 2.2.0-1.17
                universal-graves: Universal Graves 1.1.1+1.17.1
                voicechat: Simple Voice Chat 1.17.1-1.1.9
        Player Count: 0 / 20; []
        Data Packs: vanilla, Fabric Mods
        Is Modded: Definitely; Server brand changed to 'fabric'
        Type: Dedicated Server (map_server.txt)
```

**Comment by Altirix** [comment]
```
11:02:24] [Server thread/INFO]: Altirix fell out of the world
[11:02:24] [Server thread/INFO]: [Altirix: Killed Altirix]
[11:02:30] [Server thread/FATAL]: Error executing task on Server
java.lang.ArrayIndexOutOfBoundsException: Index 33554432 out of bounds for length 20374
        at me.drex.antixray.util.ChunkPacketBlockControllerAntiXray.onBlockChange(ChunkPacketBlockControllerAntiXray.java:545) ~[anti-xray-mc1.17.1-1.1.0.jar:?]
        at net.minecraft.class_1937.redirect$zpi000$onBlockChanged(class_1937.java:5101) ~[intermediary-server.jar:?]
        at net.minecraft.class_1937.method_30092(class_1937.java:211) ~[intermediary-server.jar:?]
        at net.minecraft.class_1937.method_8652(class_1937.java:196) ~[intermediary-server.jar:?]
        at net.minecraft.class_1937.method_8650(class_1937.java:271) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14266(class_3225.java:249) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_21717(class_3225.java:221) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14263(class_3225.java:154) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12066(class_3244.java:1012) ~[intermediary-server.jar:?]
        at net.minecraft.class_2846.method_12361(class_2846.java:34) ~[intermediary-server.jar:?]
        at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bbh000$modifiedRunLoop(MinecraftServer.java:5399) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

got this when i broke a Universal death grave from  https://modrinth.com/mod/universal-graves

**Comment by Patbox** [comment]
Oh yeah, it looks like incompatibility with Polymer library. The best way to fix it (from my really quick look at the class itself) would be usage of Identity/any other Map with BlockState -> boolean. It should ideally have the same performance as MC's implementation is backed by one anyway

**Comment by DrexHD** [comment]
Hello, Thanks for the detailed issues. I have just uploaded a commit that should fix them. 
Before officially releasing this though I would love to hear back from you, wherever this actually fixed your issue.
Please make sure to grab the latest version from [Github actions](https://github.com/DrexHD/AntiXray/actions/runs/1492166032) and test your issues. @the-english-breaker @Nakijama @Altirix 

Kind regards,
Drex
